---
services:
  lazyfestival_bot:
    image: lazyfestival_bot:latest
    container_name: lazyfestival_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data.json:/app/data.json
      - ./alerts.json:/app/alerts.json:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
